Sprint 12
MaximAgarev/ImageFeed pull request #5
Opened 2023-03-14 23:20 UTC by MaximAgarev

First review

2023-03-15 20:28 UTC, protos17 requested changes

2023-03-15 20:28 UTC, protos17 commented on ImageFeed/ImagesListService/ImagesListService.swift
> +    func fetchPhotosNextPage() {
Тут надо добавить проверку, что task уже есть: guard photosTask == nil else { return }, сейчас ловит ошибку

2023-03-15 20:28 UTC, protos17 commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +            cell.dateLabel.text = "Date is empty"
Здесь по тз мы должны присваивать пустую строку, а не "Date is empty"

2023-03-15 20:28 UTC, protos17 commented on ImageFeed/ImagesList/ImagesListCell.swift
> +    @IBAction func likeButtonClicked(_ sender: Any) {
Здесь стоит добавить `private`
Необходимо указывать private  для того, чтобы спрятать детали реализации конкретной части функциональности, 
когда они используются только внутри области объявления.

2023-03-15 20:28 UTC, protos17 commented on ImageFeed/ImagesList/ImagesListViewController.swift
>      private let photosName: [String] = Array(0..<20).map{"\($0)"}
Можно удалить мок данные, не используется

2023-03-15 20:28 UTC, protos17 commented on ImageFeed/ImagesList/ImagesListViewController.swift
>              let viewController = segue.destination as! SingleImageViewController
Рекомендую сделать проверку опционала через guard let или if let

2023-03-15 20:28 UTC, protos17 commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +                assertionFailure("\(error)")
Рекомендую показать алерт с ошибкой

2023-03-15 20:28 UTC, protos17 commented on ImageFeed/ImagesListService/ImagesListService.swift
> +}
Рекомендую модели вынести в отдельный файл, а здесь оставить только ImageListService

2023-03-15 20:28 UTC, protos17 commented on ImageFeed/ImagesListService/ImagesListService.swift
> +                    assertionFailure("\(error)")
Тут рекомендую показать алерт с ошибкой

2023-03-15 20:28 UTC, protos17 commented on ImageFeed/ImagesListService/ImagesListService.swift
> +            break
Рекомендую показать алерт с ошибкой

2023-03-16 09:13 UTC, MaximAgarev commented on ImageFeed/ImagesListService/ImagesListService.swift
> +    func fetchPhotosNextPage() {
Сорри, не совсем понял. Разве photosTask?.cancel() на 69 строке не решает эту задачу? Если таска есть, она отменится, а если nil, то ничего не случится и код продолжит выполняться.

2023-03-16 09:16 UTC, MaximAgarev commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +            cell.dateLabel.text = "Date is empty"
"2. Честно обработать теоретическую ситуацию, в которой мы не смогли преобразовать строку с датой в Date. Обычно в таком случае из функции, где мы выполняем преобразование даты, «бросается» исключение с использованием throw (ведь такая ситуация является аномальной); «выше по стеку вызовов» эта ошибка отлавливается и, как результат, показывается пользователю."

2023-03-16 09:16 UTC, protos17 commented on ImageFeed/ImagesListService/ImagesListService.swift
> +    func fetchPhotosNextPage() {
Нужно прерывать функцию, а не отменять задачу и создавать новую

2023-03-17 10:14 UTC, protos17 approved these changes

2023-03-17 10:14 UTC, protos17 commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +                let alert = UIAlertController(
Рекомендую вынести в отдельную функцию, чтобы вызывать этот метод на ошибки

2023-03-17 10:14 UTC, protos17 commented on ImageFeed/Profile/ProfileViewController.swift
>      func didTapButton() {
Здесь стоит добавить `private`
Необходимо указывать private  для того, чтобы спрятать детали реализации конкретной части функциональности, 
когда они используются только внутри области объявления.

2023-03-17 10:14 UTC, protos17 commented on ImageFeed/SingleImageView/SingleImageViewController.swift
> +            imageView.kf.setImage(with: URL(string: largeImageURL)) { result in
Сильная ссылка, рекомендую добавить weak self

2023-03-18 10:06 UTC, merged